package dev.godjango.apk.models;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** @noinspection all*/
public class CountryData {
    private Map<String, List<String>> countryToPhoneCodesMap;
    private final List<String> countryNames;

    public CountryData() {
        countryToPhoneCodesMap = new HashMap<>();
        countryNames = new ArrayList<>();
        initializeData();
    }

    private void initializeData() {
          countryToPhoneCodesMap = new HashMap<>();

        addCountryCode("Iceland", "+354");
        addCountryCode("Luxembourg", "+352");
        addCountryCode("Mali", "+223");
        addCountryCode("Comoros", "+269");
        addCountryCode("Australia", "+61");
        addCountryCode("Estonia", "+372");
        addCountryCode("Canada", "+1");
        addCountryCode("Belarus", "+375");
        addCountryCode("Guyana", "+592");
        addCountryCode("Gambia", "+220");
        addCountryCode("Tunisia", "+216");
        addCountryCode("Cameroon", "+237");
        addCountryCode("Rwanda", "+250");
        addCountryCode("Cambodia", "+855");
        addCountryCode("Benin", "+229");
        addCountryCode("Greece", "+30");
        addCountryCode("South Korea", "+82");
        addCountryCode("Mauritius", "+230");
        addCountryCode("United States Virgin Islands", "+1-340");
        addCountryCode("San Marino", "+378");
        addCountryCode("Maldives", "+960");
        addCountryCode("Vanuatu", "+678");
        addCountryCode("Malawi", "+265");
        addCountryCode("Egypt", "+20");
        addCountryCode("Senegal", "+221");
        addCountryCode("Georgia", "+995");
        addCountryCode("New Zealand", "+64");
        addCountryCode("Cape Verde", "+238");
        addCountryCode("Italy", "+39");
        addCountryCode("Monaco", "+377");
        addCountryCode("Slovakia", "+421");
        addCountryCode("Uruguay", "+598");
        addCountryCode("Laos", "+856");
        addCountryCode("Faroe Islands", "+298");
        addCountryCode("Niue", "+683");
        addCountryCode("North Macedonia", "+389");
        addCountryCode("Chile", "+56");
        addCountryCode("Cyprus", "+357");
        addCountryCode("Macau", "+853");
        addCountryCode("El Salvador", "+503");
        addCountryCode("Jordan", "+962");
        addCountryCode("Jamaica", "+1-876");
        addCountryCode("Barbados", "+1-246");
        addCountryCode("Qatar", "+974");
        addCountryCode("Guatemala", "+502");
        addCountryCode("Micronesia", "+691");
        addCountryCode("Montserrat", "+1-664");
        addCountryCode("Papua New Guinea", "+675");
        addCountryCode("Brazil", "+55");
        addCountryCode("Lithuania", "+370");
        addCountryCode("French Guiana", "+594");
        addCountryCode("Moldova", "+373");
        addCountryCode("Kyrgyzstan", "+996");
        addCountryCode("Curacao", "+599");
        addCountryCode("Vietnam", "+84");
        addCountryCode("Angola", "+244");
        addCountryCode("Malaysia", "+60");
        addCountryCode("Switzerland", "+41");
        addCountryCode("Thailand", "+66");
        addCountryCode("Dominican Republic", "+1-809");
        addCountryCode("Dominican Republic", "+1-829");
        addCountryCode("Dominican Republic", "+1-849");
        addCountryCode("Uzbekistan", "+998");
        addCountryCode("Chad", "+235");
        addCountryCode("Guinea", "+224");
        addCountryCode("Turks and Caicos Islands", "+1-649");
        addCountryCode("Puerto Rico", "+1-787");
        addCountryCode("Puerto Rico", "+1-939");
        addCountryCode("Bhutan", "+975");
        addCountryCode("Cayman Islands", "+1-345");
        addCountryCode("Marshall Islands", "+692");
        addCountryCode("Anguilla", "+1-264");
        addCountryCode("Mauritania", "+222");
        addCountryCode("Martinique", "+596");
        addCountryCode("Israel", "+972");
        addCountryCode("Ecuador", "+593");
        addCountryCode("Grenada", "+1-473");
        addCountryCode("Croatia", "+385");
        addCountryCode("Brunei", "+673");
        addCountryCode("Iraq", "+964");
        addCountryCode("Japan", "+81");
        addCountryCode("Lesotho", "+266");
        addCountryCode("Tuvalu", "+688");
        addCountryCode("Finland", "+358");
        addCountryCode("South Sudan", "+211");
        addCountryCode("United States Minor Outlying Islands", "+268");
        addCountryCode("Saint Helena", "+290");
        addCountryCode("Saint Helena", "+247");
        addCountryCode("Afghanistan", "+93");
        addCountryCode("Solomon Islands", "+677");
        addCountryCode("China", "+86");
        addCountryCode("Eritrea", "+291");
        addCountryCode("Russia", "+73");
        addCountryCode("Russia", "+74");
        addCountryCode("Russia", "+75");
        addCountryCode("Russia", "+78");
        addCountryCode("Russia", "+79");
        addCountryCode("Andorra", "+376");
        addCountryCode("Armenia", "+374");
        addCountryCode("Austria", "+43");
        addCountryCode("Suriname", "+597");
        addCountryCode("Spain", "+34");
        addCountryCode("Tokelau", "+690");
        addCountryCode("Bahamas", "+1-242");
        addCountryCode("Sint Maarten", "+1-721");
        addCountryCode("Belize", "+501");
        addCountryCode("Sweden", "+46");
        addCountryCode("Botswana", "+267");
        addCountryCode("United Arab Emirates", "+971");
        addCountryCode("Iran", "+98");
        addCountryCode("Gabon", "+241");
        addCountryCode("Saint Kitts and Nevis", "+1-869");
        addCountryCode("Equatorial Guinea", "+240");
        addCountryCode("Sao Tomé and Príncipe", "+239");
        addCountryCode("Greenland", "+299");
        addCountryCode("Bangladesh", "+880");
        addCountryCode("Romania", "+40");
        addCountryCode("British Indian Ocean Territory", "+246");
        addCountryCode("Sudan", "+249");
        addCountryCode("Bosnia and Herzegovina", "+387");
        addCountryCode("Malta", "+356");
        addCountryCode("Seychelles", "+248");
        addCountryCode("Sri Lanka", "+94");
        addCountryCode("Mexico", "+52");
        addCountryCode("Yemen", "+967");
        addCountryCode("British Virgin Islands", "+1-284");
        addCountryCode("Netherlands", "+31");
        addCountryCode("Paraguay", "+595");
        addCountryCode("United Kingdom", "+44");
        addCountryCode("Venezuela", "+58");
        addCountryCode("Bouvet Island", "+47");
        addCountryCode("Ukraine", "+380");
        addCountryCode("Morocco", "+212");
        addCountryCode("Portugal", "+351");
        addCountryCode("Pakistan", "+92");
        addCountryCode("Saint Vincent and the Grenadines", "+1-784");
        addCountryCode("North Korea", "+850");
        addCountryCode("Slovenia", "+386");
        addCountryCode("Ivory Coast", "+225");
        addCountryCode("Palestine", "+970");
        addCountryCode("Belgium", "+32");
        addCountryCode("Zimbabwe", "+263");
        addCountryCode("Tanzania", "+255");
        addCountryCode("Togo", "+228");
        addCountryCode("Cook Islands", "+682");
        addCountryCode("New Caledonia", "+687");
        addCountryCode("Saint Lucia", "+1-758");
        addCountryCode("Poland", "+48");
        addCountryCode("Samoa", "+685");
        addCountryCode("Czechia", "+420");
        addCountryCode("Indonesia", "+62");
        addCountryCode("Bolivia", "+591");
        addCountryCode("Colombia", "+57");
        addCountryCode("Honduras", "+504");
        addCountryCode("Denmark", "+45");
        addCountryCode("Central African Republic", "+236");
        addCountryCode("Libya", "+218");
        addCountryCode("Guinea Bissau", "+245");
        addCountryCode("Mongolia", "+976");
        addCountryCode("DR Congo", "+243");
        addCountryCode("Nauru", "+674");
        addCountryCode("Syria", "+963");
        addCountryCode("Montenegro", "+382");
        addCountryCode("France", "+33");
        addCountryCode("Zambia", "+260");
        addCountryCode("Myanmar", "+95");
        addCountryCode("Saint Pierre and Miquelon", "+508");
        addCountryCode("Costa Rica", "+506");
        addCountryCode("Somalia", "+252");
        addCountryCode("Ireland", "+353");
        addCountryCode("French Polynesia", "+689");
        addCountryCode("Hungary", "+36");
        addCountryCode("Turkey", "+90");
        addCountryCode("Oman", "+968");
        addCountryCode("Guam", "+1-671");
        addCountryCode("Nepal", "+977");
        addCountryCode("Liechtenstein", "+423");
        addCountryCode("Madagascar", "+261");
        addCountryCode("Kazakhstan", "+76");
        addCountryCode("Kazakhstan", "+77");
        addCountryCode("Djibouti", "+253");
        addCountryCode("Gibraltar", "+350");
        addCountryCode("Namibia", "+264");
        addCountryCode("Republic of the Congo", "+242");
        addCountryCode("Germany", "+49");
        addCountryCode("Vatican City", "+379");
        addCountryCode("French Southern and Antarctic Lands", "+262");
        addCountryCode("Albania", "+355");
        addCountryCode("Algeria", "+213");
        addCountryCode("Haiti", "+509");
        addCountryCode("Svalbard and Jan Mayen", "+4-779");
        addCountryCode("Tonga", "+676");
        addCountryCode("Hong Kong", "+852");
        addCountryCode("Singapore", "+65");
        addCountryCode("Antigua and Barbuda","+1-268");
        addCountryCode("Saudi Arabia", "+966");
        addCountryCode("Cuba", "+53");
        addCountryCode("Panama", "+507");
        addCountryCode("Liberia", "+231");
        addCountryCode("Azerbaijan", "+994");
        addCountryCode("Latvia", "+371");
        addCountryCode("Kiribati", "+686");
        addCountryCode("Ethiopia", "+251");
        addCountryCode("Niger", "+227");
        addCountryCode("Trinidad and Tobago", "+1-868");
        addCountryCode("Sierra Leone", "+232");
        addCountryCode("Mozambique", "+258");
        addCountryCode("Palau", "+680");
        addCountryCode("Fiji", "+679");
        addCountryCode("Norfolk Island", "+672");
        addCountryCode("Turkmenistan", "+993");
        addCountryCode("Tajikistan", "+992");
        addCountryCode("Lebanon", "+961");
        addCountryCode("Nigeria", "+234");
        addCountryCode("United States", "+1-201");
        addCountryCode("United States", "+1-202");
        addCountryCode("United States", "+1-203");
        addCountryCode("United States", "+1-205");
        addCountryCode("United States", "+1-206");
        addCountryCode("United States", "+1-207");
        addCountryCode("United States", "+1-208");
        addCountryCode("United States", "+1-209");
        addCountryCode("United States", "+1-210");
        addCountryCode("United States", "+1-212");
        addCountryCode("United States", "+1-213");
        addCountryCode("United States", "+1-214");
        addCountryCode("United States", "+1-215");
        addCountryCode("United States", "+1-216");
        addCountryCode("United States", "+1-217");
        addCountryCode("United States", "+1-218");
        addCountryCode("United States", "+1-219");
        addCountryCode("United States", "+1-220");
        addCountryCode("United States", "+1-224");
        addCountryCode("United States", "+1-225");
        addCountryCode("United States", "+1-227");
        addCountryCode("United States", "+1-228");
        addCountryCode("United States", "+1-229");
        addCountryCode("United States", "+1-231");
        addCountryCode("United States", "+1-234");
        addCountryCode("United States", "+1-239");
        addCountryCode("United States", "+1-240");
        addCountryCode("United States", "+1-248");
        addCountryCode("United States", "+1-251");
        addCountryCode("United States", "+1-252");
        addCountryCode("United States", "+1-253");
        addCountryCode("United States", "+1-254");
        addCountryCode("United States", "+1-256");
        addCountryCode("United States", "+1-260");
        addCountryCode("United States", "+1-262");
        addCountryCode("United States", "+1-267");
        addCountryCode("United States", "+1-269");
        addCountryCode("United States", "+1-270");
        addCountryCode("United States", "+1-272");
        addCountryCode("United States", "+1-274");
        addCountryCode("United States", "+1-276");
        addCountryCode("United States", "+1-281");
        addCountryCode("United States", "+1-283");
        addCountryCode("United States", "+1-301");
        addCountryCode("United States", "+1-302");
        addCountryCode("United States", "+1-303");
        addCountryCode("United States", "+1-304");
        addCountryCode("United States", "+1-305");
        addCountryCode("United States", "+1-307");
        addCountryCode("United States", "+1-308");
        addCountryCode("United States", "+1-309");
        addCountryCode("United States", "+1-310");
        addCountryCode("United States", "+1-312");
        addCountryCode("United States", "+1-313");
        addCountryCode("United States", "+1-314");
        addCountryCode("United States", "+1-315");
        addCountryCode("United States", "+1-316");
        addCountryCode("United States", "+1-317");
        addCountryCode("United States", "+1-318");
        addCountryCode("United States", "+1-319");
        addCountryCode("United States", "+1-320");
        addCountryCode("United States", "+1-321");
        addCountryCode("United States", "+1-323");
        addCountryCode("United States", "+1-325");
        addCountryCode("United States", "+1-327");
        addCountryCode("United States", "+1-330");
        addCountryCode("United States", "+1-331");
        addCountryCode("United States", "+1-334");
        addCountryCode("United States", "+1-336");
        addCountryCode("United States", "+1-337");
        addCountryCode("United States", "+1-339");
        addCountryCode("United States", "+1-346");
        addCountryCode("United States", "+1-347");
        addCountryCode("United States", "+1-351");
        addCountryCode("United States", "+1-352");
        addCountryCode("United States", "+1-360");
        addCountryCode("United States", "+1-361");
        addCountryCode("United States", "+1-364");
        addCountryCode("United States", "+1-380");
        addCountryCode("United States", "+1-385");
        addCountryCode("United States", "+1-386");
        addCountryCode("United States", "+1-401");
        addCountryCode("United States", "+1-402");
        addCountryCode("United States", "+1-404");
        addCountryCode("United States", "+1-405");
        addCountryCode("United States", "+1-406");
        addCountryCode("United States", "+1-407");
        addCountryCode("United States", "+1-408");
        addCountryCode("United States", "+1-409");
        addCountryCode("United States", "+1-410");
        addCountryCode("United States", "+1-412");
        addCountryCode("United States", "+1-413");
        addCountryCode("United States", "+1-414");
        addCountryCode("United States", "+1-415");
        addCountryCode("United States", "+1-417");
        addCountryCode("United States", "+1-419");
        addCountryCode("United States", "+1-423");
        addCountryCode("United States", "+1-424");
        addCountryCode("United States", "+1-425");
        addCountryCode("United States", "+1-430");
        addCountryCode("United States", "+1-432");
        addCountryCode("United States", "+1-434");
        addCountryCode("United States", "+1-435");
        addCountryCode("United States", "+1-440");
        addCountryCode("United States", "+1-442");
        addCountryCode("United States", "+1-443");
        addCountryCode("United States", "+1-447");
        addCountryCode("United States", "+1-458");
        addCountryCode("United States", "+1-463");
        addCountryCode("United States", "+1-464");
        addCountryCode("United States", "+1-469");
        addCountryCode("United States", "+1-470");
        addCountryCode("United States", "+1-475");
        addCountryCode("United States", "+1-478");
        addCountryCode("United States", "+1-479");
        addCountryCode("United States", "+1-480");
        addCountryCode("United States", "+1-484");
        addCountryCode("United States", "+1-501");
        addCountryCode("United States", "+1-502");
        addCountryCode("United States", "+1-503");
        addCountryCode("United States", "+1-504");
        addCountryCode("United States", "+1-505");
        addCountryCode("United States", "+1-507");
        addCountryCode("United States", "+1-508");
        addCountryCode("United States", "+1-509");
        addCountryCode("United States", "+1-510");
        addCountryCode("United States", "+1-512");
        addCountryCode("United States", "+1-513");
        addCountryCode("United States", "+1-515");
        addCountryCode("United States", "+1-516");
        addCountryCode("United States", "+1-517");
        addCountryCode("United States", "+1-518");
        addCountryCode("United States", "+1-520");
        addCountryCode("United States", "+1-530");
        addCountryCode("United States", "+1-531");
        addCountryCode("United States", "+1-534");
        addCountryCode("United States", "+1-539");
        addCountryCode("United States", "+1-540");
        addCountryCode("United States", "+1-541");
        addCountryCode("United States", "+1-551");
        addCountryCode("United States", "+1-559");
        addCountryCode("United States", "+1-561");
        addCountryCode("United States", "+1-562");
        addCountryCode("United States", "+1-563");
        addCountryCode("United States", "+1-564");
        addCountryCode("United States", "+1-567");
        addCountryCode("United States", "+1-570");
        addCountryCode("United States", "+1-571");
        addCountryCode("United States", "+1-573");
        addCountryCode("United States", "+1-574");
        addCountryCode("United States", "+1-575");
        addCountryCode("United States", "+1-580");
        addCountryCode("United States", "+1-585");
        addCountryCode("United States", "+1-586");
        addCountryCode("United States", "+1-601");
        addCountryCode("United States", "+1-602");
        addCountryCode("United States", "+1-603");
        addCountryCode("United States", "+1-605");
        addCountryCode("United States", "+1-606");
        addCountryCode("United States", "+1-607");
        addCountryCode("United States", "+1-608");
        addCountryCode("United States", "+1-609");
        addCountryCode("United States", "+1-610");
        addCountryCode("United States", "+1-612");
        addCountryCode("United States", "+1-614");
        addCountryCode("United States", "+1-615");
        addCountryCode("United States", "+1-616");
        addCountryCode("United States", "+1-617");
        addCountryCode("United States", "+1-618");
        addCountryCode("United States", "+1-619");
        addCountryCode("United States", "+1-620");
        addCountryCode("United States", "+1-623");
        addCountryCode("United States", "+1-626");
        addCountryCode("United States", "+1-628");
        addCountryCode("United States", "+1-629");
        addCountryCode("United States", "+1-630");
        addCountryCode("United States", "+1-631");
        addCountryCode("United States", "+1-636");
        addCountryCode("United States", "+1-641");
        addCountryCode("United States", "+1-646");
        addCountryCode("United States", "+1-650");
        addCountryCode("United States", "+1-651");
        addCountryCode("United States", "+1-657");
        addCountryCode("United States", "+1-660");
        addCountryCode("United States", "+1-661");
        addCountryCode("United States", "+1-662");
        addCountryCode("United States", "+1-667");
        addCountryCode("United States", "+1-669");
        addCountryCode("United States", "+1-678");
        addCountryCode("United States", "+1-681");
        addCountryCode("United States", "+1-682");
        addCountryCode("United States", "+1-701");
        addCountryCode("United States", "+1-702");
        addCountryCode("United States", "+1-703");
        addCountryCode("United States", "+1-704");
        addCountryCode("United States", "+1-706");
        addCountryCode("United States", "+1-707");
        addCountryCode("United States", "+1-708");
        addCountryCode("United States", "+1-712");
        addCountryCode("United States", "+1-713");
        addCountryCode("United States", "+1-714");
        addCountryCode("United States", "+1-715");
        addCountryCode("United States", "+1-716");
        addCountryCode("United States", "+1-717");
        addCountryCode("United States", "+1-718");
        addCountryCode("United States", "+1-719");
        addCountryCode("United States", "+1-720");
        addCountryCode("United States", "+1-724");
        addCountryCode("United States", "+1-725");
        addCountryCode("United States", "+1-727");
        addCountryCode("United States", "+1-730");
        addCountryCode("United States", "+1-731");
        addCountryCode("United States", "+1-732");
        addCountryCode("United States", "+1-734");
        addCountryCode("United States", "+1-737");
        addCountryCode("United States", "+1-740");
        addCountryCode("United States", "+1-743");
        addCountryCode("United States", "+1-747");
        addCountryCode("United States", "+1-754");
        addCountryCode("United States", "+1-757");
        addCountryCode("United States", "+1-760");
        addCountryCode("United States", "+1-762");
        addCountryCode("United States", "+1-763");
        addCountryCode("United States", "+1-765");
        addCountryCode("United States", "+1-769");
        addCountryCode("United States", "+1-770");
        addCountryCode("United States", "+1-772");
        addCountryCode("United States", "+1-773");
        addCountryCode("United States", "+1-774");
        addCountryCode("United States", "+1-775");
        addCountryCode("United States", "+1-779");
        addCountryCode("United States", "+1-781");
        addCountryCode("United States", "+1-785");
        addCountryCode("United States", "+1-786");
        addCountryCode("United States", "+1-801");
        addCountryCode("United States", "+1-802");
        addCountryCode("United States", "+1-803");
        addCountryCode("United States", "+1-804");
        addCountryCode("United States", "+1-805");
        addCountryCode("United States", "+1-806");
        addCountryCode("United States", "+1-808");
        addCountryCode("United States", "+1-810");
        addCountryCode("United States", "+1-812");
        addCountryCode("United States", "+1-813");
        addCountryCode("United States", "+1-814");
        addCountryCode("United States", "+1-815");
        addCountryCode("United States", "+1-816");
        addCountryCode("United States", "+1-817");
        addCountryCode("United States", "+1-818");
        addCountryCode("United States", "+1-828");
        addCountryCode("United States", "+1-830");
        addCountryCode("United States", "+1-831");
        addCountryCode("United States", "+1-832");
        addCountryCode("United States", "+1-843");
        addCountryCode("United States", "+1-845");
        addCountryCode("United States", "+1-847");
        addCountryCode("United States", "+1-848");
        addCountryCode("United States", "+1-850");
        addCountryCode("United States", "+1-854");
        addCountryCode("United States", "+1-856");
        addCountryCode("United States", "+1-857");
        addCountryCode("United States", "+1-858");
        addCountryCode("United States", "+1-859");
        addCountryCode("United States", "+1-860");
        addCountryCode("United States", "+1-862");
        addCountryCode("United States", "+1-863");
        addCountryCode("United States", "+1-864");
        addCountryCode("United States", "+1-865");
        addCountryCode("United States", "+1-870");
        addCountryCode("United States", "+1-872");
        addCountryCode("United States", "+1-878");
        addCountryCode("United States", "+1-901");
        addCountryCode("United States", "+1-903");
        addCountryCode("United States", "+1-904");
        addCountryCode("United States", "+1-906");
        addCountryCode("United States", "+1-907");
        addCountryCode("United States", "+1-908");
        addCountryCode("United States", "+1-909");
        addCountryCode("United States", "+1-910");
        addCountryCode("United States", "+1-912");
        addCountryCode("United States", "+1-913");
        addCountryCode("United States", "+1-914");
        addCountryCode("United States", "+1-915");
        addCountryCode("United States", "+1-916");
        addCountryCode("United States", "+1-917");
        addCountryCode("United States", "+1-918");
        addCountryCode("United States", "+1-919");
        addCountryCode("United States", "+1-920");
        addCountryCode("United States", "+1-925");
        addCountryCode("United States", "+1-928");
        addCountryCode("United States", "+1-929");
        addCountryCode("United States", "+1-930");
        addCountryCode("United States", "+1-931");
        addCountryCode("United States", "+1-934");
        addCountryCode("United States", "+1-936");
        addCountryCode("United States", "+1-937");
        addCountryCode("United States", "+1-938");
        addCountryCode("United States", "+1-940");
        addCountryCode("United States", "+1-941");
        addCountryCode("United States", "+1-947");
        addCountryCode("United States", "+1-949");
        addCountryCode("United States", "+1-951");
        addCountryCode("United States", "+1-952");
        addCountryCode("United States", "+1-954");
        addCountryCode("United States", "+1-956");
        addCountryCode("United States", "+1-959");
        addCountryCode("United States", "+1-970");
        addCountryCode("United States", "+1-971");
        addCountryCode("United States", "+1-972");
        addCountryCode("United States", "+1-973");
        addCountryCode("United States", "+1-975");
        addCountryCode("United States", "+1-978");
        addCountryCode("United States", "+1-979");
        addCountryCode("United States", "+1-980");
        addCountryCode("United States", "+1-984");
        addCountryCode("United States", "+1-985");
        addCountryCode("United States", "+1-989");
        addCountryCode("Argentina", "+54");
        addCountryCode("Burkina Faso", "+226");
        addCountryCode("Bermuda", "+1-441");
        addCountryCode("Nicaragua", "+505");
        addCountryCode("Bahrain", "+973");
        addCountryCode("Kenya", "+254");
        addCountryCode("Serbia", "+381");
        addCountryCode("Timor Leste", "+670");
        addCountryCode("Dominica", "+1-767");
        addCountryCode("Northern Mariana Islands", "+1-670");
        addCountryCode("Philippines", "+63");
        addCountryCode("Kosovo", "+383");
        addCountryCode("Kuwait", "+965");
        addCountryCode("Taiwan", "+886");
        addCountryCode("Burundi", "+257");
        addCountryCode("American Samoa", "+1-684");
        addCountryCode("Bulgaria", "+359");
        addCountryCode("South Africa","+27");
        addCountryCode("Peru", "+51");
        addCountryCode("Aruba", "+297");
        addCountryCode("Ghana", "+233");
        addCountryCode("Saint Martin", "+590");
        addCountryCode("India", "+91");
        addCountryCode("Uganda", "+256");

        countryNames.addAll(countryToPhoneCodesMap.keySet());
        countryNames.add("Country not found");
    }

    private void addCountryCode(String countryName, String phoneCode) {
        countryToPhoneCodesMap.computeIfAbsent(countryName, k -> new ArrayList<>()).add(phoneCode);
    }

    public Map<String, List<String>> getCountryToPhoneCodesMap() {
        return countryToPhoneCodesMap;
    }

    public List<String> getCountryNames() {
        return countryNames;
    }
}